# Generated by Django 3.1.5 on 2021-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='lugar_nacim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='año_edicion',
            field=models.CharField(default='n.f', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='lugar_edicion',
            field=models.CharField(default='n.p.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Novela'), (2, 'Ensayo')]),
        ),
    ]
